---
title: "Liberia Community-based Management of Acute Malnutrition Coverage Assessment"
subtitle: "A report prepared for the Liberia Ministry of Health and UNICEF Liberia"
author: 
    - name: MSc in International Health and Tropical Medicine Class 2023
    - name: University of Oxford
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_depth: 3
    self_contained: true
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  echo = FALSE
)

for (f in list.files("R", full.names = TRUE)) source (f)
```

## Introduction

A three-year nutrition programme has been implemented in Liberia by the Ministry of Health and UNICEF aimed at tackling child undernutrition in the country. Funded by [Power of Nutrition](http://www.powerofnutrition.org) and [UNICEF UK](https://www.unicef.org.uk), the programme has been implemented across 15 counties in Liberia starting from January 2017 up to December 2019. The overall aim of the programme is to improve the coverage of direct nutrition interventions or what is commonly termed nutrition-specific interventions, i.e. interventions or programmes that address the immediate determinants of foetal and child nutrition and development — adequate food and nutrient intake, feeding, caregiving and parenting practices, and low burden of infectious diseases. The current programme supports the following specific key interventions: 1) *treatment of severe acute malnutrition (SAM) within the community-based management of acute malnutrition (CMAM) programme for children 6-59 months*; 2) *vitamin A supplementation for children 6-59 months*; 3) *promotion of appropriate infant and young child feeding (IYCF) practices among pregnant or lactating women*; 4) *multiple micronutrient powder (MNP) supplementation for children 6-23 months*; and, 5) *iron and folic acid (IFA) supplementation for pregnant women*.

To assess the programme's progress towards its overall aim, two coverage assessments have been implemented - the first at the halfway point of the programme and the second at the end. Only two programme areas were selected for the assessments: *Urban Montserrado (Greater Monrovia)* district and *Grand Bassa* county.

This document reports on the results of the coverage assessment of the CMAM programme for treating SAM children 6-59 months old.

## Description of the sample
<!--- INSERT TEXT AND LITERATE CODE BELOW THIS LINE --->





## Nutrition screening coverage
<!--- INSERT TEXT AND LITERATE CODE BELOW THIS LINE --->





## Prevalence of acute undernutrition
<!--- INSERT TEXT AND LITERATE CODE BELOW THIS LINE --->





## Coverage of SAM treatment
<!--- INSERT TEXT AND LITERATE CODE BELOW THIS LINE --->





